var _variable;
document.writeln("Value after variable declaration is: "+_variable+"<br>");
_variable = 5;
document.writeln("Initial Value: "+_variable+"<br>");
_variable++;
document.writeln("After Increament: "+_variable+"<br>");
_variable= 7 +_variable;
document.writeln("Value after addition"+_variable+"<br>");
_variable--;
document.writeln("Value after decrement is: "+_variable+"<br>");
document.writeln("Value after decrement is: "+_variable%3);
